### ISSUE TITLE
For August 2018

### ISSUE THREAD

**Issue by HarryMacfinned** [bisq-network/compensation#115]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: `6900`
 - BSQ address: B19yxYCRTVaDfRfucrH6aEzeZpoVTv8Je8S

This  compensation request :
- follows the https://docs.bisq.network/roles.html#compensation recommandations
- applies the 1BSQ=1USD rule

Some tasks are a bit new. I did my best for fair single evaluations.
Apart from single evaluations, I have also a global evaluation goal, which is simply to have compensation request inline with time spent.
This month (like june and july), my time spent on the Bisq project was full time.

## Contributions delivered

- Proposal | https://github.com/bisq-network/proposals/issues/35 | (BSQ requested = 300)

### Substantive reports

- Support staff | https://github.com/bisq-network/roles/issues/64#issuecomment-417612055 | (BSQ  requested = 2000)
Evaluation is based and intended in line with : previous compensation requests, https://github.com/bisq-network/compensation/issues/24 , and other support compensation requests.

- Reddit ambassador | https://github.com/bisq-network/roles/issues/35#issuecomment-417584223  | (BSQ requested = 4500)
Evaluation is based and intended in line with : comparison with other work (support), time spent, comparison with analog existing role : twitter admin -> https://github.com/bisq-network/roles/issues/21#issuecomment-401554300
NB : If I continue with this role, I may/should ask less for the next month(s) (~3500 BSQ). But for this month, the starting of the thing ate me really a considerable time, and I request compensation for that specific phase.

## Nothing to report

- Fee monitoring | https://github.com/bisq-network/bisq-monitor/issues/11 | (BSQ requested = 100)

## Other points

- I'm participating in the support, and I'm playing an ambassador role on reddit. Like for other people concerned, this requires staying aware and participating about Bisq's life on all the places where I have access (slack, forum, etc).
This eats significant time. This time is (partly) integrated in the respective concerned BSQ requests.
(This being said, I'm still far from being aware of the whole).

- I publish also daily the Bisq offer book + F2F offer book on the Bisq discourse forum + some other sparse promotion. This publishing being part of the reddit daily publication is thus integrated herein.

- I published some issues (desktop etc) on github. I worked and helped also on the translation proposal managed by @ripcurlx .

- I'll probably take one holiday week in the second week of september. Without internet. So sorry, but (apart moral support ;-)) no participation to Bisq from me during this period.

## Contributions in progress

- The reddit role is far from being exhausted. There is customer deposit to deepen there (and on other places)
- I have still dev works dragging on. Reddit ate me a considerable amount of time this month. At least I have a python code running to generate the daily F2F offer book. Automated full offer book should follow.
- I'll pursue the proposal concerning the listing fees (apart if another one is more rapid)

**Comment by alexej996** [comment]
Hey @HarryMacfinned,
I am not sure if we should value activity on reddit so much.

To some extent we never really pushed for much marketing, we kinda just always found that word of mouth and honest recommendations by regular users is the best approach for now.
Furthermore, it might even cloud people's judgement a bit, when they see that Bisq is pushing to be advertised so much across reddit, instead of focusing on providing the best service possible.

I am not saying that your activity on reddit is necessarily bad for Bisq, no one can know that for sure I guess.
But I am just saying that by accepting this compensation request, we are actively supporting and encouraging it. Compensation request are retroactive, so we can only control what the DAO does by accepting/rejecting work that is already done.

I think it is important for us to feel comfortable with rejecting compensation requests and not to experience it as something personal, because this is the way that we decide on what DAO does.
I will have to vote against this one, as I personally think that it is best for Bisq that we don't spend so much on paid activity on reddit.

**Comment by ManfredKarrer** [comment]
@alexej996 @HarryMacfinned 
Maybe you could start a discussion what and in which direction the activity on Reddit should go. I share the concern of @alexej996 but at the same time appreciate that there is more activity on Reddit (which has been pretty dead the last year). I personally don't value Reddit a lot but I know that there is still a big community attached to it. I would see it in relation to Twitter (or in future Mastodon) less relevant for Bisq. So our expenses in that should reflect that as well. 
I think to focus on support in those platforms and try to keep anything what smells like PR low. Some communities like Monero are super sensitive to that (and right by being so).

**Comment by HarryMacfinned** [comment]
Thanks Alexej and Manfred for your comments.
I'll provide argumentation as for the why and the how of the reddit work this month. 
I'll be however afk for some hours, so it will be later today.

**Comment by ManfredKarrer** [comment]
@HarryMacfinned 
I highly appreciate it that you are active on Reddit and I agree that it is a platform relevant for Bisq. I think what @alexej996 concern is that we are spending proportionally maybe too much for that platform and that we have to take care that activity there is not interpreted as "marketing". I know you take care of that and there is no clear black/white here and interpretations might vary. To focus on answering questions and providing support is for sure the safest way to not get into PR-land.
Maybe we should define what the DAO stakeholders see a reasonable budget we want to spend on Reddit? The 3500 you suggest for upcoming months is probably not far away from a reasonable target, but others might have other opinions. My personal target would be probably a bit lower, around 2500 BSQ. But no strong opinion here... Estimations of others are welcome...

**Comment by HarryMacfinned** [comment]
1/ I agree it's a good idea to fix a budget, even approximately, for things we want to be done.
And then candidate contributors know they should fit their work inside the envelope.
[I will try to push for this (usual) practice of budgetizing things for other roles/tasks, eg for nodes.]

2/ Concerning reddit, I forgot to give this link : https://www.alexa.com/topsites/countries/US
In US reddit is atm on rank 5 (and was rank 3 in may 2018).
Compared to other places, reddit is certainly among the best places for the quality of comments
(even if there is of course also trolls and bullshit).

3/ If we vote for instance on a marketing budget proposal, I think we could vote for several channels.
For my part, I see at least 4 channels on which Bisq should be present : twitter, bitcointalk, youtube, reddit. I'm sure I'm missing important channels.
If Bisq is for any reason less present on some channels, I don't find absurd to push stronger on others.

Anyway, I think Bisq has to exhibit its vitality on some external channels (not just our own internal github/slack/forum).

2 additionnal **general** remarks on budget/numbers :

1/ For the numbers themselves, my feeling is that, atm, it's interesting to convert fuzzy BSQs in real growth.
(Growth coming from every tasks : developers work, design, good docs, good network, marketing, etc)
I'm a bit worried about how long the slot for Bisq taking off can last ? certainly not indefinitely.
Bisq must not consume it's BSQ fuel too fast, but on the other hand if it doesn't take off 
but we still have BSQ fuel left ... this will be of few comfort.

atm Bisq has linear growing + volatility. Good months and less good months.
I wonder if this linear growing + word of mouth is enough to drag Bisq out of the danger zone in time ?
If we could help the natural way, it wouldn't hurt.

As a user I'm happy seing so much projects poping up. 
As a specific project contributor, I think "what if one neighbour project takes off a bit faster, and eats our customer basis ?".

2/ For the numbers, as said in another discussion, we can also keep in mind that, with the proposals and with the monthly vote, we can put the numbers at 0 at any moment.
If some stakeholders notices that a role is not done appropriately, the point can be discussed at any moment, and we can quite rapidly vote a proposal saying: "Please, stop this task".

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/107#issuecomment-418244359

**Comment by ManfredKarrer** [comment]
@HarryMacfinned 
Can you start some discussion about the BSQ value the stakeholders are willing to support for promoting Bisq on Reddit? In the recent voting round I was the only one who accepted your request and a few rejected it, so it would be good to get to a more solid consensus regarding that topic.
Maybe ping those who rejected to get their opinions...

**Comment by HarryMacfinned** [comment]
@ManfredKarrer and @all

It was already my intent to take the stakeholders vote in account.

Last month, I requested compensation for a significant amount, because it was for a big work, and it seemed thus fair to me.
Since this did provoke -1 votes and only one +1 vote
(and there are so many other things to do) :
- I'm reducing/simplifying the activity ... and thus the compensation asked
- I'll divide and detail a bit more the subtasks involved (as other do)
- I asked an exceptionnal 1000 BSQ premium in august for launching the thing, corresponding to the extra launch work involved. I will not ask (and it was not my intent) for it again.

So I think this will bring the associated comp. request in the 2500-3000 BSQ zone.
imo this should be considered as a monthly **budget** for reddit, and for my part I'll be perfectly happy if such budget would be **shared** between **several** animators or even if **someboby else** takes entirely the role.
Other Bisq people have already a reddit account and use it timely.

As I already told it above, I'm not specially interested on the reddit animator role.
I did it because reddit is **obviously** a growth and liquidity deposit for Bisq, and I find it a pitty and a waste seing this channel without animation.
Ignoring reddit would imo be a costful error. We shouldn't do it.

If 2500-3000 BSQ is still considered as too much for the reddit animation as I do it atm, it will indeed be kind from stakeholders and appreciated to tell it here before the next vote.

**Comment by ManfredKarrer** [comment]
Thanks @HarryMacfinned for the reply.

I would appreciate if those who rejected or voted neutral post what they think is appropriate what we should spend per month on Reddit activities.

I will not vote on the next request here to leave more influence to the other contributors. I just did not want to "downvote" the last request as it was not sufficiently discussed. We are all in a learning phase how to run the DAO and to start earlier to discuss to find consensus might be a good way to deal with it.

**Comment by alexej996** [comment]
I think 2500-3000 is more reasonable, but again, this is just my opinion.
I personally voted against this one and I assume neutral votes are mostly just sticking to the previous agreement to not vote on things that you are not very familiar with.

Since this compensation request was accepted, we can simply vote in future with this budget in mind.
As long as these posts don't become something that could be considered as aggressive marketing (creating off-topic posts just to advertise), I think it would be fine to spend less than 3000 for reddit advertisement.

**Comment by HarryMacfinned** [comment]
> I don't have exact numbers about on how much time I spend there, but on a typical month, it's many hours spent monitoring, reading and responding what others write about Bisq,
> you need the person writing the tweets to be deeply connected to the domain, know the audience, etc.

On a typical month, it's exactly the same on reddit. But reddit's search engine is unfortunately not very powerful and only searches thru the titles. To search for "Bisq" in a subreddit, you have to search in that subreddit.
I personnaly have a 1500 followers account since several years. I'm not caring enough on this account the last year, but this helps me having a rather good idea on the twitter/reddit comparison.

> we're reaching in excess of 1M people with our efforts there, and you can see these stats in my monthly reports on the role.

Concerning the stats on reddit, I don't know atm about tools which may give a synthetic view as with twitter stats.
The best I'm aware atm, are the stats as given in a poster's profile.
https://www.reddit.com/user/Dieter_von_Bisq
But those stats say unfortunately nothing directly about the views. You must click each post, xpost, comment to see the views.
The best easy synthetic proxy we may have concerning the views, are the upvotes/downvotes, and the comments, which are correlated to the views. atm, downvotes are less then 1%, unseable.
(Btw, it can be pointed that the stats as given by twitter (prints) are not everywhere taken as 100% trustful)

On another point, when I begin with reddit on july 22th, the Bisq presence on reddit was (and still is) hardly comparable to the presence on twitter. I presume that probably both channels didn't got the same care.
I'm not sure it would be a good idea to argue about actual low stats on a channel (due to less care) as a good reason to not be active on the channel.

> I have a hard time seeing how our efforts in r/Bitcoin and r/Bisq subreddits

Efforts in r/Bitcoin are very very small.
Efforts in r/bisq itself concerns a group of 790 subscribers (which is very small).
r/bisq is atm absolutely not the place where the posts get the most views.
(For the past week the numbers for the daily Bisq Offer Book on 12/13/14/15th are 151+144+178+89 -> 562/4=140 views.)

This morning the daily BOB made 56 views on r/bisq and at the same moment 522 views for the 6 crossposts.
It's the crossposts which make really plenty use of the initial publication.

> exceed the value of our Twitter efforts by 3x (the 4500 BSQ originally requested above), or even 2x (~2500–3000 BSQ,

Posting in r/bisq is imo necessary because r/bisq is Bisq's **basis** in reddit.
People who want to read informations about Bisq on reddit must have this place.
But posting in r/bisq is certainly not sufficient to actively find new customers.
To actively find new customers (who don't come entirely by themselves atm),
you have to search those customers in the place where they are, ie in the subreddits they read.

My strategy atm is to crosspost the daily Bisq Offer Book to potentially concerned subreddits.
The atm calendar is below.

monday         | tuesday        | wednesday     | thursday      | friday
---------------|----------------|---------------|---------------|----------
xmrtrader      | EtcTrader      | Namecoin      | algoTrading   | ByteBall
LitecoinMarkets| BitcoinMarkets | CryptoCurrency| CryptoTrading | CryptoCurcies    
Daytrading     | Unobtanium     | siatrader     | CryptoMarkets | gridcoin
Trading        | dogecoin       | XSPEC         | Horizen       | dashpay
ByteBall       | zec            | zcoin         | Dex           | pivx

This calendar is evolving :
- ie (too) small subreddits are replaced by bigger ones
- I though adding also national bitcoin subreddits (would be a 6th row)

The goal is to, once a week, send a reminder to all those subreddits, that Bisq exists as a marketplace, to give them an example on what is on the market, and to provide links to join.

In a typical day, this represents 2 or 3 posts per day + 6 crossposts.
For the month this amounts to : 50 posts + 120 crossposts.
In addition to those posts/xposts, there are also questions/reactions etc.
Which needs answers. Answers = comments.
I posted 70 comments in august. That's 2 or 3 comments per week day.
Each comment concerns a particular question/topic. You don't chose the topic. You have to answer.

In august (count v0.8.0 in) the numbers were : 50 posts, 150 crossposts, 70 comments.
I consider that all the daily crossposts equates one post -> 150 xposts=30 posts
(there is a 10' mandatory delay between posts/xposts)
I'll also count each comment as a post.
**So the total for august = 50 + 30 + 70 = 150 posts**

It may also be worth signaling that :
- posting on our own subreddit is easy, posting on other subreddits where they have their own moderators and their own rules is a bit more delicate.
- there is no 280 characters limit for the posts on reddit. There is no length limit, which gives you plenty of place to argument when needed. Of course, in general reddit posts are longer than tweets.

When I did my first estimation for this role, I tried to find points of comparison in order to fill my comp. request properly and fairly.
The comparison point I had atm was @cbeams 's own work on twitter, who posted (on average value) 70 posts/month on twitter atm.

**So for posting a bit more than twice, longer posts, I require(d) roughly twice.**
(Please don't count the august premium as typical. I explicitely stated it wasn't.)

I remention also that this estimation was coherent with the hours spent and with my other role (support).

I may well understand the remarks about the **budget versus the audience**.
But still, we should be careful with that :
- It's not because reddit has no easy synthetic view counting (afaik) that there are no views.
- the audience of a neglected channel is low, this is quite normal. This is imo not a reason to say that the channel itself is not worth.

(If we continue discussing this audience topic, another place than here maybe more appropriate.)

I am a bit more annoyed about the remarks about **the budget versus the work done**.
I tried to ask rather precisely the same BSQs for the same quantity/quality of posts. I don't ask for more.

I'm also interested about answering @cbeams question about it's own figure, but I'll do it in another post (since it may have also other concerns).

**Comment by alexej996** [comment]
I didn't realize that twitter activity is payed less than reddit.
Maybe it doesn't make much sense to ask thousands for reddit at this point after all.

If Chris values the time spent on these things 1500 BSQ and yet it gives us so much more than reddit, we maybe shouldn't invest in reddit so much at this point. It might make more sense to have less activity on reddit then twitter if it isn't as profitable to do so, not more.

I agree with Chris that we shouldn't be paying more for less value to the Bisq.
I don't see this problem just as something that can be solved with a fixed budget, since the performance for that budget is important as well.

**Comment by ManfredKarrer** [comment]
Lets make a though example: You have a budget if 5000 USD per month for promotion, where and how would you distribute it?
I would assign probably 3000 USD on Twitter and 2000 on Reddit.

@cbeams performance on Twitter is great and easily more worth then 1500 BSQ - though it is very hard to estimate and I think it is easier that we ask ourselves what we want to spend and use a budget instead of trying to find the real value.

@HarryMacfinned Could you imagine to lower your efforts on Reddit in the way that it matches a budget the stakeholders are assigning for Reddit activities? I definitely appreciate that we get more presence on Reddit but I also want to keep it in right proportions to other expenses (Twitter, dev efforts, support,...).

**Comment by cbeams** [comment]
I'd be happy to try this kind of budgeting approach. It'll have it's own pitfalls, of course, but it may be better than the more arbitrary calculus I've been using around Twitter.

I think the important thing around these conversations is to keep progressing and keep trying new things until we land at a workable equilibrium. As I've said elsewhere, these are hard problems we're trying to solve around compensation, and though it can be a bit frustrating to do so, I think having these conversations are vital to getting there. Thanks everyone for your candor.

**Comment by m52go** [comment]
> Perhaps my 1500/mo figure is off by a wide margin after all.

I think it's easily off by a factor of 2 or 3.

At the same time, part of the reason for Twitter's effectiveness _right now_ is months of savvy management by @cbeams to get to this point. But valuing marketing is hard because you can put the same considerable effort in month-to-month but get wildly different results. 

You may get nothing for a very long time as you build an audience, whereas you'll get relatively huge results for the same work with a huge audience. We're past that dark period for Twitter, but I don't think we're there yet anywhere else.

This means it's unreasonable to value marketing work on a developing platform by results, but it's also unreasonable to value marketing work on an established platform by results. Marketing needs to be valued by effort/hours put in. But because marketing efforts have varying levels of impact, unlike delivered code (for example), we need stakeholders to agree which marketing work is best to in the first place. Which means, as @ManfredKarrer suggested above, that we need to collectively determine a monthly budget stakeholders find acceptable to spend on marketing.

Personally, I did not vote for this proposal because I didn't think the Reddit work was worth that much. @HarryMacfinned I value the time you're spending there, but I see Reddit as being more useful as a support forum than a marketing tool. Reddit can be hugely powerful as a marketing tool, but that power (in my experience) comes from targeted posts & comments in HUGE subreddits (like 1,000,000+ subs). That's the only way get any attention there. Otherwise, with a small following, you're basically in a room by yourself talking to yourself (even if posts there are getting >100 views, they're getting little to no exposure outside the subreddit...which means there's a near-zero chance of going viral). Contrast that with a platform like Twitter: even with a small following, you're still talking to yourself most of the time BUT you're in the same room as everyone else, so you have a decent chance of going viral with any single post. YouTube also has this benefit.

Once we have a monthly budget, we can determine how many platforms we can financially support marketing on. Then we can determine which platforms those should be. Where do our most probably new users hang out? Twitter is an obvious one, email should be another one, but I'm not sure about another one. Reddit may show promise, but frankly I've never seen anyone interested in Bisq link to Reddit. Maybe YouTube?

I think we should also consider partnering with existing channels for exposure instead of trying to build our own channels. Twitter is crucial, and we've nailed that. Others are questionable/TDB. Perhaps it's better to spend time getting interviews on the many great podcasts & YouTube channels, doing guest blog posts, etc. on channels that already exist. The bang-for-buck factor will be through the roof, and if we pick smartly, we'll KNOW we're reaching the right people. Bisq has a stellar brand and the trust of many of the smartest, most prolific figures in Bitcoin—we should make use of it.

**Comment by HarryMacfinned** [comment]
@Manfredkarrer wrote :
> Lets make a though example: You have a budget if 5000 USD per month for promotion, where and how would you distribute it?
I would assign probably 3000 USD on Twitter and 2000 on Reddit.
@cbeams performance on Twitter is great and easily more worth then 1500 BSQ - though it is very hard to estimate and I think it is easier that we ask ourselves what we want to spend and use a budget instead of trying to find the real value.
@HarryMacfinned Could you imagine to lower your efforts on Reddit in the way that it matches a budget the stakeholders are assigning for Reddit activities? I definitely appreciate that we get more presence on Reddit but I also want to keep it in right proportions to other expenses (Twitter, dev efforts, support,...).

Concerning @cbeams 's performance on Twitter, my opinion since the beginning (and as Chris himself expressed it somewhere in github, saying "I would pay more for the job"), is that this role (as achieved by him atm) is more worth then 1500 BSQ. I know enough about twitter to say that.

The case with reddit, as I do it atm, is that the role is quite a **whole**.
- 1st: you post on r/bisq (it brings views, nice ok, but that's just the start)
- 2nd: you crosspost. Here you **multiply** the views in the great subreddits
- 3rd: you reply to reactions and/or to people asking about Bisq.

It must however be pointed that the pure views metrics is not the whole picture. Bumping in small but motivated subreddits (eg national subreddits may also pay)

In reddit, what could be lowered/cut separately ?
- Posting without crossposting ? it's the crossposts which brings 90% of the views. Not crossposting means losing 90% of the benefits of the job.
- Not taking time to answer people asking about Bisq ? sometimes after your own first post. Better not post at first
- I may post only 1 day every 2 days ... which would lead touching subreddits every 2 weeks. I'm not really carried away ...

The reddit channel itself doesn't seem to provoke enthousiasm here.
The atm conditions makes it also not possible to pursue **gently** my role on reddit.
The simple way I see lowering my atm activity on reddit is simply stopping it. If there is no discord, it's what I'll do.

I'm also very happy that we had this discussion now. And I thank everybody telling their opinion in advance. It's a bit better than at a end of month votation.

Some post-scriptum **general** remarks :
- atm, Bisq's shareholding is not spending USD, it's spending BSQs.
- it may well be that having one main communication channel is enough. I think a good second channel would not harm.
- I don't agree with Alexej and m52go analysis concerning the reddit channel itself. Concerning the pertinence of reddit versus other channels, 2 links :
https://youtu.be/Lvf8koqX_yE + https://www.alexa.com/topsites/countries/US
imo reddit is a pertinent/appropriate channel for Bisq. To find customers, but not only.

**Comment by ManfredKarrer** [comment]
@HarryMacfinned 
Yes Reddit indeed does not create enthusiasm at least for me. I just visited the new posting on r/Bitcoin (https://www.reddit.com/r/Bitcoin/comments/9glgfq/bisq_the_decentralized_exchange/) and it is frustrating to see the level of ignorance, arrogance and generally low match with Bisq values. Of course there are great supporters as well, but at least for me I get mostly depressed by the Reddit users.

That does not mean I am against promotion on Reddit as I think it is still a big channel where we can find potential new users. For reducing the efforts to meet a smaller budget I would leave it to you how to do it with the highest efficiency.

**Comment by joachimneumann** [comment]
Hi,

I think that the value of reddit as a tool to help Bisq grow is limited and I would propose a monthly limit of 500 BSQ.
The work as a reddit ambassador does not require a high level of qualification either.

Joachim
