### ISSUE TITLE
Cycle 47 deadline is May 14th

### ISSUE THREAD

**Issue by MwithM** [bisq-network/compensation#1289]
The deadline for submitting compensations requests for review is **May 14**. 

More details at: https://bisq.wiki/Compensation
[Calendar](https://calendar.google.com/calendar/embed?src=adfiuiokq9jtac8t9keomc00b0%40group.calendar.google.com&ctz=Europe)

**Comment by MwithM** [comment]
A couple days reminder.

**Comment by cbeams** [comment]
@MwithM, as can be seen in the history above, I just accidentally moved this cord from In Progress to Review (and then back). I was surprised I was able to do this at all, and on investigation it turns out I'm still explicitly whitelisted as a collaborator on this project. Could you remove me at https://github.com/orgs/bisq-network/projects/5/settings/users? Thanks.

**Comment by gabernard** [comment]
> @MwithM, as can be seen in the history above, I just accidentally moved this cord from In Progress to Review (and then back). I was surprised I was able to do this at all, and on investigation it turns out I'm still explicitly whitelisted as a collaborator on this project. Could you remove me at https://github.com/orgs/bisq-network/projects/5/settings/users? Thanks.

I removed you.

**Comment by MwithM** [comment]
End of cycle 47
