### ISSUE TITLE
For November 2017

### ISSUE THREAD

**Issue by Emzy** [bisq-network/compensation#15]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 1300
 - BSQ address: B16X76GXZ3hDTkDRiRtb1bYN1bAuDpP7nSE

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

Setup  and running of 3 Bitcoin fullnodes . 
3 onion address 
3 clearnet address
3 server are on a VPS the other is a dedicated server.
See: https://github.com/bisq-network/roles/issues/39

Running the Pricenode and one Seednode servers.
Paying for a $12 USD / Mounth bitcoinaverage.com Subscription (for the Pricenode)

Running the bisq-contrib mailinglist server

**Comment by ManfredKarrer** [comment]
Not sure if we should add monthly service costs here as well as it started somehow mid months. I leave it up to the operators if they want to do it or not. But all should do the same then...

All services by @Emzy have been running with very high availability and quality of service.

**Comment by Emzy** [comment]
Yes I have calculated monthly costs in full for the month. Hadn't thought about calculating it as a fraction of the month, makes it even more complex. Maybe we agree that the month the server stops will not be compensated. Wo it will be fairer, but still easier.
What do you think?

**Comment by ManfredKarrer** [comment]
Ah ok. I though it was without...
I would get to a higher result but probably my assumptions how you use your servers are wrong.

BTC nodes:
3 x 200  + 1 x 300
Seed + price relay:
2 x 200 
Mailinglist server:
200

Monthly costs nodes: 50 / node -> 300
Monthly costs  mailinglist server: 50

BTW: 
The 5th BTC node at https://github.com/bisq-network/roles/issues/39 is using the same BTC instance, we just moved it to @Emzy because it was too unstable before at another host. We would like to still find another operator for that still.

**Comment by Emzy** [comment]
The Setup of the Mailserver and Seed Nodes is already in the October 2017 one.

Setup:
BTC nodes:
3 x 200 + 1 x 300
=900

Monthly costs nodes: 5* VPS  (50 / node) -> 250
Monthly costs dedicated node 100 
Monthly costs mailinglist server: 50
=400

Right there was something missing. It is 1300.

**Comment by ManfredKarrer** [comment]
Ah thanks for the clarification!
