### ISSUE TITLE
For October 2018

### ISSUE THREAD

**Issue by leshik** [bisq-network/compensation#158]
Hi there,
This is my first compensation request, and frankly I have no idea on how much to request. Please correct me if I'm wrong.

## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 200
 - BSQ address: B1CK6i6P4cGc73sRTtovNaRUC9QrjhzUJxd

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

I've contributed PromptPay payment method for Thailand: https://github.com/bisq-network/bisq/pull/1831
Here are other linked threads:
https://github.com/bisq-network/bisq/issues/1467
https://github.com/bisq-network/payment-methods/issues/6
https://bisq.community/t/promptpay-in-thailand/6458
Hope this will bring more activity to Bisq network in Thailand.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

**Comment by ManfredKarrer** [comment]
Hi @leshik ! Thanks for request! 
As background info: 1 BSQ is considered as 1 USD (nobody knows yet the real market price so have the consensus to estimate it to 1 USD for now). You should use the market rate of your work in case you would have worked for any commercial company as orientation (no discount because you like Bisq or want to support OS projects).

I think your requested amount is too low. The PR was perfect without any required change. So feel free to increase it.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/149#issuecomment-435645489.
