### ISSUE TITLE
Requested amounts

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/compensation#261]
I have the feeling we are entering a kind of spiral upwards regarding requested amounts. 

We have to remind ourself to relate the requested amount to the amount of value added to Bisq. I am sure there is much work in the backgound which is often not always visible. But then please help others to make it more visible or wait for the request until the work has materialized in somehing more tangible so other contributors can evaluate better the added value to Bisq.

In this round I will vote only on those contributors with whom I worked directly as only there I am able to estimate the value (that should be the default behaviour anyway, thought I did not follow that for myself in the past). So please don't take it personal if I don't vote on your request, I just don't want to spend time to evaluate if the request is justified.

Please also be aware that we collectively sending out signals about the management of the DAO from an economic perspective. The trade volume growth to expenses ration should be in a healthy realtionship.

**Comment by eyalron33** [comment]
I completely align with Manfred.

The amounts being asked have grown exponentially recently. I feel now it's now double or even triple normal rates for such contributions in other organizations. There is a danger for it to become a race. Past contributes feeling they were not properly contributed due to the new standards, then asking for even higher amounts next time, creating higher standards.

Yes, I'm aware that Bisq is not an "organization" but rather a DAO, but it shouldn't matter much when it comes to the amounts themselves. 

There is also the case that compensations are the BSQ being issued every month. It's equivalent to Bitcoin emission rate; if it'll be too high, having a token becomes moot.

For the long term we need guidelines for which amounts are "acceptable". Plus, maybe communicating what is reasonable for contributers to expect in return to their work.

Personally, I rather not see Bisq as a project attracting those with a sense for "easy money". In my eyes it should be a project that compensates less than other places, but attracts those who genuinely care about it.  

I'm writing all of this without blaming anyone in particular, and without claiming that anyone did anything wrong. I'm more of pointing a problem and expressing a fear for the long term.

**Comment by ManfredKarrer** [comment]
I think the basic guildlines are clear: The added value to Bisq. People can compare what they would get paid in a freeelance work for compareable work. There is also work which is more long term, contains daily business, etc. For those of course it is a bit harder to estimate as not all small work package can be estimated. Still such work should produce some clearly visible added value to Bisq and baed on that the "daily business" part can be included. Not easy to find our right way - its all an experiment and we need to adjust if things develop in a wrong direction... So no offense at all to anyone, we are all learning...

**Comment by m52go** [comment]
I was going to raise this concern privately about some requests, so I'm glad Manfred raised it here first.

Only thing I want to add is there's a reason we can reject proposals, and people shouldn't take it personally. **It doesn't necessarily mean your work wasn't worthwhile, it just means you haven't made a good enough case for your work's value**. I've hesitated to reject proposals in the past, but I don't think that's healthy for the system.

In my opinion, no one should hesitate to reject proposals they don't agree with, as long as there's a reasonable reason, and have meaningful discussions after the fact to set things straight. People will learn and adjust with time.

**Comment by eyalron33** [comment]
@ManfredKarrer You're possibly the only person in Bisq who can estimate what's the added value to Bisq, so you're (possibly) the only person who may think that "the added value to Bisq" is a clear guideline :- )  

A horizontal view of Bisq is needed in order to evaluate such thing; almost no one besides you have it.

I, for example, have difficulties to even estimate the added value of my contributions, not to mention of others (even if I collaborated with them).

In a "normal" organization, I would negotiate a compensation sum with someone like you before doing the job itself. Bisq doesn't have this mechanism. Though we may want to add COO as a future bonded role.... (don't kill me for raising this idea please!).

For starters, I hope that a culture of not asking for too much will be developed. Maybe it's worth mentioning this thread in next calls for compensation requests?

**Comment by huey735** [comment]
Yeah, it's not always evident how to measure the value added. But I think as time goes by we could look to previous similar paid contributions for guidance.
Rejecting requests may come off has harsh but is the correct mechanism to pressure them down to reasonable values.

**Comment by ManfredKarrer** [comment]
@eyalron33 Sure there are cases where it is more difficult and you cannot compare all according to that metrics. What is the value if you find a critical consensu sbug in the DAO? Unlimited at the end if it would make the difference if the DAO suceeds or fails - and with it the value of any BSQ. 

But as a rule of thumb just use the number what you would request in a freelance work relationship. The negotiation part is here more delayed to that discussion we have at the moment or to the voting process. But also when negotiation you need to have some number and even if it is there often very hard the numbers cannot be compeltely out of scope. E.g. if you hire a code audit company they also will not charge 10 Millions for each critical bug they found even if that would be the realistic value...

But yes I agree it is a difficult thing we are trying to do and we need to learn how to do it right. But good thing is that it worked surprisingly well in the past. There have been more cases where I suggested a contributpr to ask for more then the other way round. And often it was then mostly because of misunderstandings of different interpretations.

Another difficulty is which country the contributor is. In Norway they have 2 times the wages than in other European counties (and living costs are 2 times higher as well) and in some Asian or Latin American counties they have few times lower living costs/wages than in the US or Europe. I think we need to adjust to an average to those countries in which most of the contributors live.

**Comment by m52go** [comment]
I think valuing work is fraught with issues, with or without a role like a COO, and the numbers will never be perfect for everyone.

My preferred approach would be to determine baseline metrics for roles and delivered work, and then let contributors make their case for adjustments.

As role maintainer, I've slacked on implementing this. For example, the blog maintainer emerged over the past couple of months, but it wasn't documented. Without a clear definition, that role has appeared to become bloated and spread across multiple people (arunasurya and me, both charging for our efforts). A clearer definition of roles and role values would force the role to contain itself to one person, and that one person would (out of necessity) limit their efforts accordingly.

Example: Twitter Admin, for example, has a well-established definition and value. I _could_ spend more time on Twitter and seek 8000 BSQ for it, but I don't because I know no one will accept that, as the baseline compensation for that role is 2000 BSQ. Thus I only spend as much time as I can justify with the ~2000 BSQ compensation in mind. (I do adjust on merit...last month, I did badly so I reduced to 1500 BSQ, but this month was especially good, so I adjusted up to 2500 BSQ).

We should consider:

1. **developing baseline metrics** for non-development tasks like videos, design, writing/blogging, translations, etc to keep value requested in check.
2. **better collaboration before people deliver** work so they're not blind-sided by the promise of BSQ for _any_ work done for Bisq (e.g., not-useful translations, graphics, etc).

To solve (1) I'd prefer to follow the Twitter Admin example...establish flat baselines for different categories of work: blog posts are worth x, videos are worth y, custom graphics are worth z, etc. 

In this way, we can signal the value of various contributions to the Bisq project, but still encourage exceptional work done on merit.

**Comment by ManfredKarrer** [comment]
I think we should also find ways to make the cost / benefit ration more visible if possible. The revenue comes from trading fees so all work need to be related to the goal how we can increase trade volume. Of course that must not lead to a primitive short minded strategy. We have to keep Bisq's long term "mission" in mind and to get to break even will take it's time. But at the end if we don't manage to get enough traders some day to fund the compensation requests we have failed economically. 

For blog posts or videos we could add statistics for the number of views and compare it to the costs. E.g. if we spend 500 BSQ on a blog post and 100 users viewed it we spend 5 BSQ per user...

Sure, that is not perfect as it does not translates into increased number of trades directly but at least we get a better idea if it was a good investment. It would also add more responsibility to the author to help to find readers and reach out. At the moment I have not seen much beside a Twitter post (sorry if I am wrong have not followed much).
 
To look at common payments in the industry might also help. I know from 2 past contributors who have been journalists at Bitcoin Magazine that 20 USD/ hour is a usual rate. 

And there is a problem when we start accepting too high requests as they will be used in the future as reference. We had similar issues with translations in the past. People orientated on older overpaid requests and it started to get out of bounds. Getting a language translated without getting a market bootstrapped and users there has close to zero value for Bisq. We managed to correct that by limiting the target languages to those markets where we put our focus.

I don't enjoy this kind of "accounting" and "business management" but I think we need to mange to get that resolved in a decentralized manner otherwise we behave like Helicopter Ben ;-).

**Comment by m52go** [comment]
Practically speaking I think (a) roles need to be better defined and (b) role owners should maintain a list of bounties for non-role work.

Bounties don't need to be all-inclusive or super-actively maintained but they would help with allocating resources and valuing contributions (i.e,. establish baselines). Making role owners responsible eliminates the need for centralized "managers" who no one wants.

I will think through more and make a proposal.

**Comment by ManfredKarrer** [comment]
Yes sounds like a good plan. With Twitter we had such a discussion in the past and it got resolved with setting a baseline what we think its worth what Twitter adds. Providing some stats will help to justify the costs over time. I think such an approach should be good enough for now.

For the blog posts: Yes we definitely want to have activity there. But the costs need to be limited and be brought in relation to the effects (page views). No blame to anyone we have not thought it wout well when we started the initative and now its time to adjust it in the right directions....

**Comment by eyalron33** [comment]
Great idea, @m52go.

**Comment by arunasurya** [comment]
I have written up my thoughts on this topic in [the comments to my March 2019 comp.request](https://github.com/bisq-network/compensation/issues/259)

**Comment by ripcurlx** [comment]
Closing as complete.
