### ISSUE TITLE
For April 2019

### ISSUE THREAD

**Issue by huey735** [bisq-network/compensation#272]
## Summary

 - BSQ requested: 154

## Contributions delivered

Translation and review of Bisq software to Portuguese (pt)
Translation of Bisq software to Portuguese (Brazil) (pt_BR)
Word count:
3760 Reviewed
7896 Translated (As my translation into pt-br was basically a copy-paste of my pt-pt translation left to Brazilian reviewers to review I'll divide this value by 2)

Using my [previous compensation request](https://github.com/bisq-network/compensation/issues/241) as a guide, I decide to value each word at 0.02 BSQ. I separated the work into two groups:

Translation - (7896/2) * 0.02 = 78.96
Reviews - 3760 * 0.02 = 75.2
Total = 154.16

Portuguese (pt) translation and review
![april-pt-translated](https://user-images.githubusercontent.com/44140017/57181938-b0617100-6e91-11e9-92ce-be87e88fcc03.png)
![april-pt-reviewed](https://user-images.githubusercontent.com/44140017/57181940-b5262500-6e91-11e9-980a-fbccb39c898b.png)

Portuguese (Brazil) (pt_BR) translation
![april-br-translated](https://user-images.githubusercontent.com/44140017/57181949-c2431400-6e91-11e9-88ef-1164fb32c2d4.png)

## Contributions in progress

Translation and review of Bisq software to Portuguese (pt)

Going forward I'll stop translating to pt_BR as there are now Brazilians doing the work. I've been pondering that despite the strong differences in the different Portuguese(s) maybe only pt_BR is enough. They represent the majority of Portuguese speakers worldwide and, I believe, of those using Bisq. I'll keep translating Portuguese (pt) but I'm considering stopping asking compensation for it and move to pt_BR and learn their different terms and give my help over there.

**Comment by criptonauta** [comment]
@huey735, I'm Brazilian and the only reason I'm using the pt_PT is that pt_BR is temporarily unavailable.

I say that considering Bisq as a financial tool. The differences between pt_PT and pt_BR can be significant in some circumstances. I rather to use it in English and have no doubts about what I'm reading than to use the software in pt_PT and risk to make some mistake with my money involved on it.

Since pt_PT is already available, why not to keep it updated? And if keeping on working on it, compensation is a right, right?

I hope my words are not misunderstood. You are more than welcome to also translate pt_BR, but please do not leave pt_PT behind. I'd say the opposite if the translation was for a more recreational/informal use (like for a game). But being for a Financial tool, I believe it's worth to keep both languages updated.

**Comment by MwithM** [comment]
`Closing old issue`
