### ISSUE TITLE
For February 2018

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#38]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 21250 (13150 + 8100 see below)
 - BSQ address: B1Dj1kAGDs4AGh83cPFJBQC7pDubtuZV2ZS

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### Development/UX
https://github.com/bisq-network/roles/issues/63

Moderation of all [gui issues](https://github.com/bisq-network/exchange/issues?q=is%3Aopen+is%3Aissue+label%3Ain%3Agui). Helped [testing with release v0.6.6](https://docs.google.com/spreadsheets/d/18n6wV0g5MPTs9Xni0cFji8U34xV3O1IRPDEYZrluBuU/edit#gid=1386834576). See all merged pull requests to master of this month below. General moderation of `#ux` channel.

[1] https://github.com/bisq-network/exchange/pull/1392
[2] https://github.com/bisq-network/exchange/pull/1365
[3] https://github.com/bisq-network/exchange/pull/1360
[4] https://github.com/bisq-network/exchange/pull/1358
[5] https://github.com/bisq-network/exchange/pull/1352
[6] https://github.com/bisq-network/exchange/pull/1350
[7] https://github.com/bisq-network/exchange/pull/1334
[8] https://github.com/bisq-network/exchange/pull/1329
[9] https://github.com/bisq-network/exchange/pull/1328
[10] https://github.com/bisq-network/exchange/pull/1316
[11] https://github.com/bisq-network/exchange/pull/1304
[12] https://github.com/bisq-network/exchange/pull/1303 

### Growth
https://github.com/bisq-network/roles/issues/42

### Analytics
https://github.com/bisq-network/roles/issues/40

### Bitcoin Fullnode Operator
Maintenance of full core node btc.christophatteneder.com:8333.

### Other
Communication with contributors

Added 8.100 $BSQ (20% of my previous compensation requests) as I thought the fair value of `1 $BSQ == 1 EUR` but it's actually `1 $BSQ == 1 USD`

**Comment by cbeams** [comment]
For the benefit of other stakeholders: regarding @ripcurlx's comment in the description above

> Added 8.100 $BSQ (20% of my previous compensation requests) as I thought the fair value of `1 $BSQ == 1 EUR` but it's actually `1 $BSQ == 1 USD`

I can verify that @ManfredKarrer and @ripcurlx and I discussed this matter in an (unrecorded) video chat following one of our recent live streams. This was a misunderstanding on @ripcurlx's part, and probably a failure on my part to properly communicate the change made to the Phase Zero doc in https://github.com/bisq-network/dao/issues/12#issuecomment-355244745 / https://github.com/bisq-network/docs/commit/b14bea055f8ce608e5d7970a92d79dc01e2eb28f.

I can also confirm that I've looked up historical USD / EUR exchange rates for the months since @ripcurlx has been submitting compensation requests and that his 20% calculation is a reasonable approximation of how much should be added here.

Thanks, @ripcurlx, and sorry for the confusion!

**Comment by ripcurlx** [comment]
Thanks for the clarification @cbeams! :+1:

**Comment by cbeams** [comment]
This request has been staged in the [BSQ stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1285577275)

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
