### ISSUE TITLE
[WIP] For Cycle 8

### ISSUE THREAD

**Issue by RiccardoMasutti** [bisq-network/compensation#416]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested:
 
 

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

### Code Development
Bisq Website:
https://github.com/bisq-network/bisq-website/pull/290
https://github.com/bisq-network/bisq-website/pull/291
https://github.com/bisq-network/bisq-website/pull/307

### Code Review
https://github.com/bisq-network/bisq-website/pull/267
https://github.com/bisq-network/bisq-website/pull/279
https://github.com/bisq-network/bisq-website/pull/280/
https://github.com/bisq-network/bisq-website/pull/284
https://github.com/bisq-network/bisq-website/pull/289
https://github.com/bisq-network/bisq/pull/3647
https://github.com/bisq-network/incubator-bisq-api/pull/21
https://github.com/bisq-network/incubator-bisq-xmr-integration/pull/2
https://github.com/bisq-network/bisq/pull/3681
https://github.com/bisq-network/bisq-website/pull/302
https://github.com/bisq-network/bisq-website/pull/303

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

### Code Development
Bisq Website:

Bisq Explorer:
https://github.com/bisq-network/bisq-explorer/pull/9

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

Bisq-desktop italian translator
https://www.transifex.com/bisq/bisq-desktop/viewstrings/#it/displaystringsproperties/110522284?q=translator%3ARiccardo

Twitter Italian Account Maintainer
https://twitter.com/BisqITA

Keybase Italian Team Maintainer
https://keybase.io/team/bisq_italia

Telegram Italian Group Maintainer
https://t.me/BisqITA

**Comment by m52go** [comment]
I would suggest you to slow down. I highly appreciate your initiative and go-for-it approach, and realize every contributor will have their own style of doing things, so take this as constructive advice.

1. Reviews are typically done by people with at least a handful of merged contributions, otherwise it's hard to attribute any significance to the reviews.

2. A number of items you listed above haven't been merged yet. [At least one wasn't even completed](https://github.com/bisq-network/bisq-website/pull/279) as claimed on this compensation request. And none of your reviews have indicated any comments, even on ones that have generated discussion like [this one](https://github.com/bisq-network/bisq-website/pull/280). On what basis did you approve [these changes](https://github.com/bisq-network/bisq/pull/3681) to the Bisq software itself? It could be that you're planning to review these items before the end of the cycle, but as it stands, it seems  that you're stacking contributions here to get as fat a paycheck as possible.

3. The roles you listed are not roles. [These are roles](https://github.com/bisq-network/roles/issues). It's fine do that stuff (i.e., create new accounts and venues for discussing Bisq) but it's premature to count them as roles performed.

I highly recommend that you consider discussing your ideas and goals with other contributors first. Are you on Keybase? I don't recognize your handle (not sure if you go by another one elsewhere). 

This would help make your work more broadly accepted. For example, why start a whole new Keybase team for Italian, instead of simply creating a new channel on the existing Keybase? Is your approach wrong? Not necessarily. But not discussing something potentially controversial and then asking to be paid for it is not a good approach.

**Comment by RiccardoMasutti** [comment]
> I would suggest you to slow down. I appreciate your initiative and go-for-it approach, and realize every contributor will have their own style of doing things, so take this as constructive advice.
> 
> 1. Reviews are typically done by people with at least a handful of merged contributions, otherwise it's hard to attribute any significance to the reviews.
> 2. A number of items you listed above haven't been merged yet. [At least one item wasn't even performed](https://github.com/bisq-network/bisq-website/pull/279) as claimed on this compensation request. And none of your reviews have included any comments, even on ones that have generated discussion like [this one](https://github.com/bisq-network/bisq-website/pull/280). And on what basis did you approve [these changes](https://github.com/bisq-network/bisq/pull/3681) to the Bisq software itself? It could be that you're planning to review the items you've listed before the end of the cycle, but as it stands, the impression you're giving is that you're stacking contributions to get as fat a paycheck as possible.
> 3. The roles you listed are not roles. [These are roles](https://github.com/bisq-network/roles/issues). It's fine do that stuff (i.e., create new accounts and venues for discussing Bisq) but it's premature to count them as roles performed.
> 
> I highly recommend that you consider discussing your ideas and goals with other contributors first. Are you on Keybase? I don't recognize your handle (not sure if you go by another one elsewhere).
> 
> This would help make your work more broadly accepted. For example, why start a whole new Keybase team for Italian, instead of simply creating a new channel on the existing Keybase team? Is your approach wrong? Not necessarily. But not discussing something potentially controversial and then asking to be paid for it is not a good approach.

Hi @m52go , I didn't know that code reviews are done only by reputable sources.  I read differently [here](https://docs.bisq.network/contributor-checklist.html).

About my reviews, it wasn't a try to get a big paycheck, exactly the opposite. I will not request anything for those reviews as there's no content, fixes or suggestions, but just simple approvals. In my opinion were ready.

About newly created social accounts, I did by reading your comment here: https://github.com/bisq-network/growth/issues/142#issuecomment-532192309

And by following @MwithM.
I saw him managing spanish Twitter account and then I realized there was a lot of foreign accounts like FR, PT, BR, etc.
I did the same for Telegram and Keybase.

Why?

Because here in Italy there's a huge informational gap about Bisq and decentralized networks/exchanges so I though it would be a great idea to launch italian channels to give support in italian.

Not only that, I will personally translate the entire website, software and subtitles in italian.
https://github.com/bisq-network/bisq-website/issues/173

What I want to show by doing this is that in Italy there is a great interest and need for Bisq.

Ps: I requested italian language project on Transifex to both subtitles and website.
I'm already working hard on software and should be ready and reviewed in 1-2 weeks.

**Comment by m52go** [comment]
Great to hear @RiccardoMasutti, and I didn't mean to accuse. Maybe it was just a matter of first impressions that didn't look right.

As you'll see in the doc you linked, it also says:

> With that said, it’s a good idea to consult with stakeholders via Slack, GitHub, the mailing list, or other communication channels before setting out on any serious contribution effort. 

Typically people use GitHub and Keybase (formerly Slack) to introduce themselves and keep people informed of in-progress and upcoming work, and compensation requests are the final result of a cycle's work. It seems like you did the opposite, and used the compensation request as a way to communicate your in-progress work instead.

I guess that's not a bad thing, but like I said above, without having ever interacted with you before, it seemed strange to me.

Thanks for your work so far. I encourage you to consider making GitHub issues and being more active on Keybase to send people signals of what you're up to, instead of relying on your compensation requests.

**Comment by RiccardoMasutti** [comment]
> Great to hear @RiccardoMasutti, and I didn't mean to accuse. Maybe it was just a matter of first impressions that didn't look right.
> 
> As you'll see in the doc you linked, it also says:
> 
> > With that said, it’s a good idea to consult with stakeholders via Slack, GitHub, the mailing list, or other communication channels before setting out on any serious contribution effort.
> 
> Typically people use GitHub and Keybase (formerly Slack) to introduce themselves and keep people informed of in-progress and upcoming work, and compensation requests are the final result of a cycle's work. It seems like you did the opposite, and used the compensation request as a way to communicate your in-progress work instead.
> 
> I guess that's not a bad thing, but like I said above, without having ever interacted with you before, it seemed strange to me.
> 
> Thanks for your work so far. I encourage you to consider making GitHub issues and being more active on Keybase to send people signals of what you're up to, instead of relying on your compensation requests.

I will do it from today.

I believe I will also propose significant changes to the structure of the documents.

I have found it very difficult to find this kind of information too, because they are scattered ...
