### ISSUE TITLE
For August 2017–February 2018

### ISSUE THREAD

**Issue by stevenkain** [bisq-network/compensation#43]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 26000
 - BSQ address: B17Z8y7JmFY53kSvHVg3VgBR6ZxkWFrvLtJ

## Details

Translation: Romanian (Ro) - 1318 strings, mostly multi-sentence, updated displayStrings_ro.properties
https://github.com/bisq-network/exchange/pull/1380

Translation: Hungarian (Hu) - 1318 strings, mostly multi-sentence, updated displayStrings_hu.properties
https://github.com/bisq-network/exchange/pull/1379

Translation: Hebrew (He) - 91 strings (in progress)
Translation: German (De) ~ 20 strings (translation & correction)

Several corrections and pull request in the English string file, uncaught by others:
https://github.com/bisq-network/exchange/pull/912
https://github.com/bisq-network/exchange/pull/901
https://github.com/bisq-network/exchange/pull/904
https://github.com/bisq-network/exchange/commit/2fb74f49363212ffdb60baa35d0591ad5d8c4a02
https://github.com/bisq-network/exchange/commit/aa87319fca773e498b895a32f1582f0ed31db31e
https://github.com/bisq-network/exchange/commit/50310338b4b4fc952566411eaa8704588f4ec898
https://github.com/bisq-network/exchange/commit/a3b1a5ff6a7c260d8d44c3ed7e77f8c04b504384
https://github.com/bisq-network/exchange/commit/fd683db2d4a57fa9adf5cf1d4eb8b0e7bcd273a4
https://github.com/bisq-network/exchange/commit/c92f95506058358e82b40aa5abedf72dc36701c6
https://github.com/bisq-network/exchange/pull/1378

Bonus: Created the :bisqitty: emoji in the Bisq Slack :)

Compensation calculation was made by the number of strings translated (and retranslated) so far plus corrections/commits in the Github repository to the English texts x10 minus the currently awarded BISQ amount (2644) in the compensation XLS. Thank you.

**Comment by ManfredKarrer** [comment]
As there is not market price for BSQ we use a consensus price of 1 USD = 1 BSQ. Real market price might be easily higher but that is a conservative lower boundary estimation. Are you sure your request or 26 000 BSQ (woudl be equivalent to 26 000 USD) is intended?

**Comment by cbeams** [comment]
Glad to see you submitting a compensation request, @stevenkain!

For everyone's reference, @stevenkain and I discussed how to value one's own contributions in [Slack on Weds Feb 21st](https://bisq.slack.com/archives/C7VK9QZRT/p1519200466000202). Here's is screenshot from the first part of that conversation:

https://bisq.slack.com/archives/C7VK9QZRT/p1519200466000202
![image](https://user-images.githubusercontent.com/301810/36820641-28b2afac-1cef-11e8-8312-2b84e954e5e3.png)

Based on what I wrote there, I would vote `-1` on this compensation request if submitted to the voting spreadsheet as-is at `26000` BSQ.

The amount you're requesting in a compensation request should be an answer to the question:

> _how much value do I believe I added to Bisq through my contributions?_

When Bisq DAO stakeholders vote `+1` on a compensation request, we're agreeing to create that much BSQ, because we believe the work was _worth_ that much BSQ.

The current working valuation of BSQ, as @ManfredKarrer mentioned, and as we've documented in the phase zero doc [here](https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#establish-and-refine-the-fair-market-value-of-the-bsq-token) is `1 BSQ == 1 USD`.

Because everyone submitting compensation requests thus far has been working with this shared `1 BSQ == 1 USD` valuation, it is unlikely that many of them would agree to approve your request, because your request is based on a different, incompatible valuation model (in which I believe you multiply the value of your current work by a factor of 10).

To be clear, I am not necessarily saying that your valuation model is invalid. I am saying that it is _incompatible_ with the model everyone here has been working under for the last four months. If you believe you have a better way to value contributions to the Bisq DAO during phase zero, please write that up elsewhere as a [proposal](https://github.com/bisq-network/proposals).

If, on review of the above, you'd like to change your requested BSQ amount, please go ahead. I won't enter these requests into the spreadsheet until tomorrow (Thursday) morning CET. Let's say the change needs to be in by noon if you're going to make the cut.

Also, a nit: this compensation request is labeled "For February", but it is in fact "For August through February". I'll update the title to reflect.

**Comment by ManfredKarrer** [comment]
@stevenkain The underlying BTC value cannot be the BSQ value as the contributor will need to fund his compensation request with the BTC himself. Thus if the value would be the same you need to send yourself the amount of BTC which would be equal to the amount of BSQ thus not earning anything.
In face we will likely use only 5 BTC for the genesis distribution because the "printing cost" in BTC are already too high with recent BTC prices and if we assume that a BTC price of 50 000 or 100 000 USD is not unrealistic.

The value of BSQ is what people think the projects value is plus the underlying BTC value which is the min. value. A BSQ cannot be less then that underlying BTC value because a BSQ is technically BTC.

If that all sounds too confusing you need to ready up the white paper and read a bit about the concepts of colored coins.

**Comment by cbeams** [comment]
> I won't enter these requests into the spreadsheet until tomorrow (Thursday) morning CET. Let's say the change needs to be in by noon if you're going to make the cut.

It's now noon CET, and this request has been staged in the [BSQ stake and vote tracking spreadsheet](https://docs.google.com/spreadsheets/d/1xlXDswj3251BPCOcII-UyWlX7o7jMkfYBE-IZ5te5Ck/edit#gid=1285577275).

@stevenkain, please note that if this request is voted down, you can always re-submit for the next voting period with an adjusted amount.

**Comment by ManfredKarrer** [comment]
@stevenkain: I wanted to add as well that I will not accept that request. Just compare with other requests and you will see that this is our of proportion. Feel free to add it again next months with a adjusted amount.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/dao/issues/39#issuecomment-368511267.
