### ISSUE TITLE
For Cycle #13

### ISSUE THREAD

**Issue by niyid** [bisq-network/compensation#553]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested:
 
**` 1950 BSQ`**

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

- bisq-network/bisq#3352 - `500 BSQ`
- bisq-network/bisq#3510 - `1,300 BSQ` (`1,000 BSQ` for discovery of critical "showstopper" bug and `300 BSQ` for resolution)
- bisq-network/bisq#3899 - `50 BSQ`
- bisq-network/bisq#3408 - `100 BSQ`

## Contributions in progress
> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

- bisq-network/bisq#3338 (Awaiting ACK from reviewer)
- bisq-network/bisq#3854 (Awaiting ACK from reviewer)
- bisq-network/bisq#3860 (Awaiting ACK from reviewer)

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

**Comment by sqrrm** [comment]
It's hard to review work done when issues solved are linked but not the solution. Linking PRs would be better.

> bisq-network/bisq#3352
> bisq-network/bisq#3510

I think these items are asking too much. The value is limited and it shouldn't take much work to implement. These items seem to have been rejected in previous CRs as well.

> bisq-network/bisq#3899

This has also been rejected before from what I understand, and it's not priority. At least a more reasonable amount requested.

> bisq-network/bisq#3408

This took a lot of review resources due to untested and poorly and was later reverted. Should not get any compensation.

As stand in [team lead](https://bisq.wiki/Compensation#Team_Lead) I reject this request.

**Comment by niyid** [comment]
I did not get the part this part regarding https://github.com/bisq-network/bisq/issues/3408 :

> This took a lot of review resources due to untested and poorly and was later reverted. Should not get any compensation.

On the others, I can review the figures if you are open to another review.

**Comment by MwithM** [comment]
There's a reimbursement request with TXID `15ffe6e6f27250c6f345bf2747217b6654ec7a1ce1035918c19c3de8b2df78b7` requesting 1950 BSQ, the same amount of this issue. 
It's ok to submit requests even when they're not approved by team leaders, but why did you do a  proposal for reimbursement instead of compensation?

**Comment by niyid** [comment]
That was an error. It was meant to be a compensation request.

**Comment by MwithM** [comment]
was:rejected
