### ISSUE TITLE
For Cycle 13

### ISSUE THREAD

**Issue by stevavoliajvar** [bisq-network/compensation#555]
## Summary

- USD requested: 200
 - BSQ requested: 317

## Roles performed
I'm secondary operator for @alexej996 forum and price node.

- Forum secondary operator : 100 USD
- Pricenode seconday operator: 100 USD

**Comment by MwithM** [comment]
Ongoing cycle is number 13 please edit title.

**Comment by cbeams** [comment]
I don't think we have a precedent for secondary @bisq-network/pricenode-operators, and in general, secondary role holders don't request compensation unless they actually did something, i.e. needed to take over for the primary in some capacity. I see that @alexej996 gave this a 👍, perhaps one or both of you could explain more about this arrangement and why you believe it merits compensation? Without something more, I would downvote this compensation request.

**Comment by alexej996** [comment]
Couple of months back I saw someone asking for a compensation on a secondary role in their CR, so I said to Stevan that he might be eligible for a compensation. He was interested so about a month ago I asked in #ops if somebody knows more about this, but no one answered, so I tought he might just let the voting decide.

It ain't a big deal either way, Stevan has been helping me out for year or so, since I went on some holiday back then. We are friends IRL, so he just helped me out as a favor every now and again when I couldn't reach my PC.

**Comment by wiz** [comment]
@stevavoliajvar Hello there. It's great that you're taking on the secondary role for the forums and that pricenode, but the ops budget is set per node instance: https://github.com/orgs/bisq-network/teams/ops/discussions/1

Of course you guys can split the compensation however you want, but the sum of your compensation requests for the same node can't exceed the budget for running a node! Since @alexej996 requested full compensation for his node I'm going to :-1: your compensation proposal for this cycle - please figure it out between the two of you how you want to split the compensation going forward.
