### ISSUE TITLE
For April 2018

### ISSUE THREAD

**Issue by alexej996** [bisq-network/compensation#60]
## Basic information

 - BSQ amount requested: **3000**
 - BSQ address: **B1CS43KxAFaTQFK4xPMKxybGffmp89zg7QS**

### Forum operator:
- Maintaining the forum, including backups,updates, server upgrades, etc.
(forum operator https://github.com/bisq-network/roles/issues/19)

### Support:
- Providing support for users on the forum, reddit, bitcointalk, Slack
(forum profile https://bisq.community/u/alexej996/summary)

### Moderation:
- Moderating Bisq forum and subreddit (reddit moderator https://github.com/bisq-network/roles/issues/25)

**Comment by cbeams** [comment]
Thanks, @alexej996. Some feedback:

Please link directly to your monthly report comment for each role you play. For example, in the case of Forum Operator, you can just have a simple one-line entry like this:

> - Forum Operator: https://github.com/bisq-network/roles/issues/19#issuecomment-385258622

There's no need to repeat the responsibilities / duties you carry out as the Forum Operator in both places.

Similar feedback with the "Moderation" item above. I know you just took that on being the primary Reddit Moderator role owner this month, but in the future, please don't combine "moderation" activities if there are actually dedicated roles for each. Just have a line item like:

> - Reddit Moderator: https://github.com/bisq-network/roles/issues/25#issuecomment-385799705

With regard to general Support Staff activities, this one is a little tricky, and I'm not 100% sure how we should deal with it. I wrote some initial thoughts at https://github.com/bisq-network/roles/issues/64#issuecomment-386571392, here are a few additional thoughts:

I think that playing a Support Staff role should in general be about being on point to help users with whatever they need, wherever they're asking for help. So this would include the Bisq Forum, the r/Bisq subreddit, @bisq_network mentions on Twitter, requests in Slack (especially in the `#support` channel, but really anywhere users are asking for help, which also often includes `#general`), the `#bisq` channel in Freenode IRC, our various GitHub repositories (especially bisq-network/support, but everywhere else, too) and anywhere else questions about Bisq come up.

Now, it's not reasonable to expect any one contributor to provide support services across all of these channels, so that's why I think it probably makes sense to have a Support Staff role like the one at bisq-network/roles#64, and to have everyone who's doing support work add a report comment on that issue every month (and then link to that report comment from their compensation request in just the same way as I mentioned above). If we do things this way, then we'll end up with a single place to capture what's going on support-wise every month. People will be able to see who is manning which battle stations, where additional support resources are necessary, etc.

One key thing here is to clearly distinguish the work of providing support, e.g. answering questions, pointing people in the right direction, etc, from the work of owning roles like "Forum Operator" or "Reddit Moderator". There may seem to be a lot of overlap between these, but I think it's best if we consider them to be completely separate. Anyone can provide support services, because anyone can respond to a user's question or otherwise help them out. One doesn't have to be playing any particular privileged role to do this, and indeed we want as many people contributing in this way as possible. On the other hand, the role of Reddit Moderator should really be defined as / confined to the specific things that moderators can and should do that other people without those privileges cannot do. For example, banning / blocking spammers, keeping the r/Bisq sidebar up-to-date, etc. In practice, the work involved in owning the Reddit Moderator role may be quite minimial, and that's fine.

Would love to hear your thoughts on all this, @alexej996, since you're probably the most engaged in support activities right now. We can continue the conversation here, or in Slack as you like, but ultimately we'll want to capture this stuff in a forthcoming `support.adoc` document at https://docs.bisq.network. This conversation will help shape what shows up there.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/58#issuecomment-387381841.

**Comment by alexej996** [comment]
I completely agree @cbeams with everything you said.
I will adjust my monthly reports according to your feedback.
