### ISSUE TITLE
For January - April 2018

### ISSUE THREAD

**Issue by blabno** [bisq-network/compensation#61]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 3950
 - BSQ address: B1ARsZ9kk1wANuuw9EDFnWF9ERwa1x5N2Rm

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

This request covers all my closed PRs since the beginning of my adventure with Bisq (january 2018), excluding work on API and mobile which is not finished yet.

* Support quick access to top nav items with Alt 1–9 keyboard shortcuts
Amount: 200 BSQ
https://github.com/bisq-network/bisq-desktop/pull/1302

* Use auto focus on the first input field on all screens
Amount: 200 BSQ
https://github.com/bisq-network/bisq-desktop/pull/1311

* Use environment locale to select right locale and currency
Amount: 200 BSQ
https://github.com/bisq-network/bisq-desktop/pull/1313

* Make arbitration chat messages selectable
Amount: 200 BSQ
https://github.com/bisq-network/bisq-desktop/pull/1326

* Configurable hostname in localhost p2p mode
Amount: 200 BSQ
https://github.com/bisq-network/bisq-desktop/pull/1330

* Not possible to select `English` anymore, if system locale is non-English
Amount: 50 BSQ
https://github.com/bisq-network/bisq-desktop/pull/1371

* Dockerize seednode for development mode 
Amount: 300 BSQ
https://github.com/bisq-network/bisq-desktop/pull/1376

* Make USE_DEV_PRIVILEGE_KEYS flag configurable
Amount: 400 BSQ
https://github.com/bisq-network/bisq-desktop/pull/1383

* Use btcNodes argument in regtest mode
Amount: 200 BSQ
https://github.com/bisq-network/bisq-desktop/pull/1416

* Redesign asset listing and validation infrastructure
Amount: 1200 BSQ
https://github.com/bisq-network/bisq-core/pull/32

* Extract bisq.asset package to its own repository
Amount: 800 BSQ
https://github.com/bisq-network/bisq-core/issues/99

**Comment by cbeams** [comment]
Thanks @blabno, great to see your first compensation request after all this time!

Not sure whether you've caught up with bisq-network/proposals#19 yet, but most of the PRs above have not yet actually been _delivered_ per the definition of that term in the proposal.

We can see, for example, that bisq-network/bisq-desktop#1302 _was_ delivered in v0.6.5:

```
$ git log --grep 'Merge pull request #1302' --pretty=format:%H | xargs git tag --contains
v0.6.5
v0.6.6
v0.6.7
```

But other bisq-desktop PRs listed above have not shipped in any release yet, and thus have _not_ been delivered, e.g.:

```
$ git log --grep 'Merge pull request #1311' --pretty=format:%H | xargs git tag --contains
[no tags listed]
```

So, in keeping with the proposal, could you create a second compensation request, titled `[WIP] For May 2018` and move `bisq-desktop` PR entries 1311–1416 to it? These will all be delivered with the forthcoming v0.7.0, which will surely ship by the time we do our May voting.

With regard to the `bisq-core` / `bisq.asset` PRs, these are an interesting case, because while the software itself has not been delivered in a release, the _value_ of these changes has indeed been delivered in the sense that the target users (people who want to list an asset) have been able to use this new infrastructure and documentation, and indeed they have in fact been using it. So I'd say keep these PRs in for this month if you like. A bit of an unusual scenario, this one, but an interesting exploration of what it means to deliver value to users in any case. You can also feel free to move these to the May PR, too. Just wanted to walk through the thinking a bit.

**Comment by ManfredKarrer** [comment]
@blabno Is that request compete now as it is still marked WIP? This months will be the last requests on the spreadsheet...

**Comment by blabno** [comment]
Yes it's complete.

**Comment by blabno** [comment]
Tasks are complete but I need to get new BSQ address.

**Comment by ManfredKarrer** [comment]
@blabno Please change the title / remove WIP. Today EOD voting starts....
@ripcurlx This request should be added as well....

**Comment by blabno** [comment]
Ok, so I've updated my BSQ address. This issue is ready.

**Comment by ripcurlx** [comment]
@blabno sorry for closing the issue by mistake

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.
