### ISSUE TITLE
For April 2018

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/compensation#63]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 250
 - BSQ address: B1CZf25cS7KrGJnT8Z5uq8DbUApZLydCkj

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

### API

Nothing that has been delivered.

### Hosting
Monthly costs nodes: 50 / node * 5: 250 BSQ

Running:
1 Price node + bitcoinaverage subscription
1 Seed node
2 Bitcoin full nodes
1 Monitoring node + 1 messaging sync node (on one server)
  
### Roles

Report for this month:
https://github.com/bisq-network/roles/issues/22#issuecomment-385487001

**Comment by cbeams** [comment]
Thanks, @mrosseel. Some feedback:

Rather than grouping stuff into a single "Hosting" section directly within your compensation request, please post a monthly update comment on each of the respective roles, e.g.:

 - Pricenode Operator at https://github.com/bisq-network/roles/issues/14
 - Seednode Operator at https://github.com/bisq-network/roles/issues/15
 - Bitcoin Node Operator at https://github.com/bisq-network/roles/issues/67
 - Monitoring Operator / Maintainer at https://github.com/bisq-network/roles/issues/10

Doing things this way maximizes the usefulness of these reports over time. Mostly, people will not go digging through individual compensation requests to see who has been hosting what, or how much they paid to host those things on various hosting providers. But if all operators consistently post monthly report comments on their respective operator role issues, it becomes very easy for operators new and old alike to see who is hosting what where, which hosting providers are overused from a a censorship resistance / network resiliency perspective, which contributors are overloaded / operating too much stuff, to evaluate which hosting providers are delivering the best "bang for the buck", etc.

Also in the "Roles" section of future compensation requests, please name the role as well as linking to the monthly report comment, so that voting stakeholders can see at a glance what roles you played, and which they wish to click on and review. For example:

> - Freenode Admin: https://github.com/bisq-network/roles/issues/22#issuecomment-385487001

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/58#issuecomment-387381841.
