### ISSUE TITLE
For May 2018

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#71]
## Summary

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 14700
 - BSQ address: B1Dj1kAGDs4AGh83cPFJBQC7pDubtuZV2ZS

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

Following PRs  have been released with v0.7.0.

#### bisq-desktop
- https://github.com/bisq-network/bisq-desktop/pull/1530
- https://github.com/bisq-network/bisq-desktop/pull/1529
- https://github.com/bisq-network/bisq-desktop/pull/1528
- https://github.com/bisq-network/bisq-desktop/pull/1521
- https://github.com/bisq-network/bisq-desktop/pull/1520
- https://github.com/bisq-network/bisq-desktop/pull/1519
- https://github.com/bisq-network/bisq-desktop/pull/1514
- https://github.com/bisq-network/bisq-desktop/pull/1506
- https://github.com/bisq-network/bisq-desktop/pull/1499
- https://github.com/bisq-network/bisq-desktop/pull/1496
- https://github.com/bisq-network/bisq-desktop/pull/1492

#### bisq-core
- https://github.com/bisq-network/bisq-core/pull/108
- https://github.com/bisq-network/bisq-core/pull/107
- https://github.com/bisq-network/bisq-core/pull/102
- https://github.com/bisq-network/bisq-core/pull/78
- https://github.com/bisq-network/bisq-core/pull/48

#### bisq-common
- https://github.com/bisq-network/bisq-common/pull/14

Including running full test suite for [v0.7.0](https://docs.google.com/spreadsheets/d/18n6wV0g5MPTs9Xni0cFji8U34xV3O1IRPDEYZrluBuU/edit#gid=1386834576) 

For these efforts I request 9840 BSQ in total.

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

Release preparations, updates and bug fixes for v0.7.1

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63#issuecomment-393453744
- Growth: https://github.com/bisq-network/roles/issues/42#issuecomment-393084180
- Analytics: https://github.com/bisq-network/roles/issues/40#issuecomment-392773117
- YouTube Admin: https://github.com/bisq-network/roles/issues/56#issuecomment-393456765
- Bitcoin Fullnode Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-393457854
- Transifex Admin: https://github.com/bisq-network/roles/issues/20#issuecomment-393459866

**Comment by ripcurlx** [comment]
@cbeams Is there an easy way to create a script that outputs all merged PRs for a release of an user? 😀

**Comment by cbeams** [comment]
> @cbeams Is there an easy way to get all merged PRs for a release of an user? 😀

Sorry, @ripcurlx, when I first read this, I thought it might have been a joke, but now I realize it may have been serious. If the latter is the case, what do you mean by "for a release of a user"?

Ah... do you mean all PRs merged that were part of a given release that involved a certain user?

That is possible, but to do it via the GitHub interface alone, it would require that all the PRs had the release field set, and we haven't been doing that very consistently (unless something has changed in bisq-desktop lately).

**Comment by cbeams** [comment]
And @ripcurlx, there seems to be a discrepancy with the BSQ requested above. In `Summary` you wrote

> BSQ requested: 14700

but in `Contributions delivered` you wrote

> For these efforts I request 9840 BSQ in total.

Could you clarify? Thanks.

**Comment by ripcurlx** [comment]
Regarding the release: Yes, it was actually a real question, as I have to do it manually and I guess it will be (hopefully) more and more PRs in the future. But it's fine also to do it manually atm, I just was curious if there is an easier way for it.

Regarding the compensation: 9840 BSQ are for the PR's and testing for v0.7.0 release. It was for the work I did for it last month. The remaining 4860 BSQ are for the roles performed this month and communication with contributors,...

Does this answer your questions?

**Comment by cbeams** [comment]
> communication with contributors

Is this [delivered](https://github.com/bisq-network/proposals/issues/19) work? I don't think we've addressed it explicitly anywhere. It's a tough call. You could make the argument that it's directly valuable work on its own, and you could make the argument that it's all part of the process of delivering finished work to end users.

I tend toward the latter definition. That it is a cost of collaborating effectively, not an end-user good on its own. From a paying and/or stakeholding Bisq user's perspective, I want there to be as little "communicating with contributors" as possible required in order to produce valuable features. I certainly don't want to economically incentivize the act of "communicating with contributors" _per se_; I want to incentivize the delivery of useful software into my hands. So from this perspective, as a Bisq user, I would want Bisq contributors to bundle their time and effort into their compensation requests in an undifferentiated way. This will allow me to vote consistently for the work that delivers more value at less overall cost, thereby rewarding very efficient contributors who don't require a lot of "communicating", or more precisely, require a minimum of it when compared with other contributors.

**Comment by cbeams** [comment]
Note that I'm not saying that you shouldn't claim this amount of BSQ, but that how we account for it matters.

The fact is that you're doing work that is presumably required in order to produce some end result of finished work to users. Should this work be accounted for when that end work gets produced? That might be hard to keep track of which conversations with which contributors led to which work getting done. So that might not be feasible. Should it be accounted for as part of the work of being a 'Maintainer' for different given repositories and projects? That might work well. It's pretty easy, because if we route Slack conversations and GitHub issues well, all the conversations you're having with contributors should already be pretty well aligned with the roles you play, e.g. being one of the @bisq-network/exchange-maintainers. And it would be pretty useful to how much of this kind of cost is going into each of our different roles. We could ask why some are so much more expensive than others, and we could share knowledge about how to transfer information faster, create better onboarding experiences for new contributors, better build dev environment rollouts, whatever helps.

**Comment by ripcurlx** [comment]
What I wanted to point out with my comment above is, that fulfilling a role has communication efforts as well and is also required in some roles to fulfill it properly. Not every role needs it, but some roles (e.g. forum admin) might be a lot about communication. Would it help if I would split up the BSQ for each role? I could do this for next months if this would help how this value is spread up over each role.

**Comment by ripcurlx** [comment]
As two didn't vote for my CR this month so far I'd like to talk about the reasons why, so I can answer any open questions. I guess the concerns are about the efforts on my roles performed this month. At the moment I calculate the amount of BSQ for these roles based on the effort/time they consume each month. Coming up with a value of these roles that is not effort based but result based is kind of tricky IMO, but I'm happy to discuss any ideas how we want to do this this month 😄

**Comment by sqrrm** [comment]
I didn't vote at all this month so if you count that as a non vote it was just because I forgot to vote.

**Comment by ripcurlx** [comment]
@sqrrm Wasn't about the fact if you haven't voted at all, just for two who voted but not for this CR. I'm happy to talk about everything if someone thinks something is not clear or not justified, that's what this   process is all about 😄

**Comment by ManfredKarrer** [comment]
I assume those who did not had the time to validate the request preferred to not vote, which is a good strategy. Otherwise of course its good that they speak up if they disagreed to give feedback....
