### ISSUE TITLE
For Cycle 19

### ISSUE THREAD

**Issue by stopfeds** [bisq-network/compensation#717]
## Summary

- **BSQ requested**: **268**
- USD requested: 180
- BSQ rate: 0.67 USD per BSQ

## Contributions delivered

| Title | Team | USD | Link | Notes |
|---|---|---|---|---|
| German Bisq-desktop translation | Growth | 180 | --- | --- |

![image](https://user-images.githubusercontent.com/71401614/100290698-467d5080-2f7c-11eb-8b08-ab44029aa7e8.png)

## Contributions in progress

| Title | Team | USD | Link | Notes |
|---|---|---|---|---|
| Translate bisq-website on Transifex | Growth | 23 | --- | --- |

Will finish this the next few days.

**Comment by MwithM** [comment]
Parsing is invalid. Don't worry, I'll fix that for you, the first compensation request is the hardest one.

```
| Title | Team | USD | Link | Notes |
|---|---|---|---|---|
| German Bisq-desktop translation | Growth | 200 | --- | --- |
```
I propose you to reduce your compensation request to 200USD - 298.5BSQ. The reason is that there are some strings that only needed to add a hyperlink (i.e. string number 600, 630) and some just had a small change or were lost, but were already translated many months ago and they could be translated using Transifex suggestions.
There's no easy way to quantify how much should be discounted from what you show from transifex screenshot, but a way to guide is the [budget](https://github.com/bisq-network/roles/issues/20#issuecomment-723830541) I create every cycle considering the strings left and added. For this cycle it was 180USD.

As long as you make the proposal parsed and reduce the compensation request amount, with @m52go permission, I approve this request. Comment when you have edited the compensation request and I'll move it to _Review Complete._
Next step will be send the [compensation](https://bisq.wiki/Compensation#Submit_your_request_as_a_DAO_proposal) request to the DAO and comment here the resulting TXID. Feel free to ask me for help at Keybase.

**Comment by ghost** [comment]
Also it needs 2 hashes before the word `Summary`, per the template.

**Comment by stopfeds** [comment]
@jmacxx @MwithM 
Thanks for your help. I hope everything is correct now.

I changed the amount to 180 USD, because I have seen the budget, I didn't expect to receive more than 180 USD anyway. So 268 BSQ should be fine.

**Comment by stopfeds** [comment]
TXID `d80fbb39d243aa3c57115816424224514620cf0c1a6bab2cf4759343621bc1c3`

**Comment by MwithM** [comment]
Closed as accepted.
