### ISSUE TITLE
For Cycle 19

### ISSUE THREAD

**Issue by rafael2333** [bisq-network/compensation#729]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`[642]`** 
- USD requested: [430] 
- BSQ rate: [0.67] USD per BSQ 
- Previous compensation request (if applicable): #  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| French Bisq-desktop translation | growth | 280 | See image below |  |
| French Bisq-website translation | growth | 150 | See image below |  |

![LYH9E(M3I` (J)HL}1JWPJ](https://user-images.githubusercontent.com/75150887/100492549-39e82c00-3125-11eb-94eb-90d85b85c48b.jpg)
![{12EF%K@7_YWUT5MCO3 DGB](https://user-images.githubusercontent.com/75150887/100492552-3b195900-3125-11eb-8e46-4f2c305c43b3.png)

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by MwithM** [comment]
Hello Rafael, I can't approve this compensation request. The compensation request submission came late, but most important, for the reasons I'll explain following. We have not talked before you started translating about 6 days ago, so I could not explain personally the conditions written on https://bisq.wiki/Translation. I changed new translator's acceptance and now they need to ask for permission. I hope this mistake won't happen again.

1. Strings tagged as "Hyperlink" are not copypasted properly, and the hyperlink won't work as it should at the app. See first image linked, the part under brackets `[]` should be exactly the same.
2. Strings tagged as "no_translate" should not be translated. They refer to unused altcoins and can't be compensated.
3. Some translations, according to my limited French knowledge, are incorrect and there's no budget for revision. The last picture I share confuses "You're receiving" with "You have to pay". I'd like that you and @bayernatoor could work together to fix wrong translations.
4. Since a big part of the website was already translated and using the suggestion from past translation is enough, 150USD was on the budget for the whole translation of the webpage. There's still 58 strings missing.

I'd like you to keep translating at next cycle and make another compensation request fixing all the details I consider incorrect now. I know you've put some effort in this but at this time I can't accept your compensation request. I hope you understand.

![imagen](https://user-images.githubusercontent.com/50149324/100538230-badf1a80-322e-11eb-9aaf-dbb9dcc214e7.png)
![paste](https://user-images.githubusercontent.com/50149324/100538659-5f625c00-3231-11eb-81eb-8042d7e45197.png)
![paste (1)](https://user-images.githubusercontent.com/50149324/100538661-60938900-3231-11eb-90fa-d3a75592d44e.png)
![paste (2)](https://user-images.githubusercontent.com/50149324/100538662-60938900-3231-11eb-9de1-2f5e13eb2890.png)
![paste (3)](https://user-images.githubusercontent.com/50149324/100538663-612c1f80-3231-11eb-84d7-76e03acd6bcc.png)

**Comment by rafael2333** [comment]
Hello Mwithm,I can totally understand your decision. I have already read your reason carefully, that's true I have made some mistakes. I will deal with the "Hyperlink","no_translate"and some incorrect translation  mistakes immediately. The missing strings I will also try to complete them.
I am really sorry to put you through. I will finish it nicely next cycle. And thanks for your patience to let me know.

**Comment by rafael2333** [comment]
> 拉斐尔你好，我不能批准这个赔偿请求。索赔请求迟迟提交，但最重要的是，原因我将在下面解释。在您大约6天前开始翻译之前，我们还没有交谈过，因此我无法亲自解释https://bisq.wiki/Translation上写的情况。我更改了新翻译的接受度，现在他们需要征得许可。我希望这个错误不会再发生。
> 
> 1. 标记为“超链接”的字符串没有正确复制，超链接在应用程序中无法正常工作。见第一个图片链接，括号下的部分`[]`应该完全一样。
> 2. 标记为“no_translate”的字符串不应翻译。它们指的是未使用的altcoins，无法补偿。
> 3. 根据我有限的法语知识，一些翻译不正确，也没有修订预算。我分享的最后一张照片混淆了“你收到”和“你必须付钱”。我希望你和@Bayernatoor能合作修复错误的翻译。
> 4. 由于网站的很大一部分已经翻译，使用过去翻译的建议就足够了，整个网页翻译的预算为150美元。仍然缺少58根弦。
> 
> 我希望您在下一个周期继续翻译，并再次提出补偿请求，修复我现在认为不正确的所有细节。我知道你在这方面付出了一些努力，但目前我不能接受你的赔偿请求。我希望你理解。
> 
> ![图像](https://user-images.githubusercontent.com/50149324/100538230-badf1a80-322e-11eb-9aaf-dbb9dcc214e7.png)
> ![粘贴](https://user-images.githubusercontent.com/50149324/100538659-5f625c00-3231-11eb-81eb-8042d7e45197.png)
> ![粘贴（1）](https://user-images.githubusercontent.com/50149324/100538661-60938900-3231-11eb-90fa-d3a75592d44e.png)
> ![粘贴（2）](https://user-images.githubusercontent.com/50149324/100538662-60938900-3231-11eb-9de1-2f5e13eb2890.png)
> ![粘贴（3）](https://user-images.githubusercontent.com/50149324/100538663-612c1f80-3231-11eb-84d7-76e03acd6bcc.png)



> 拉斐尔你好，我不能批准这个赔偿请求。索赔请求迟迟提交，但最重要的是，原因我将在下面解释。在您大约6天前开始翻译之前，我们还没有交谈过，因此我无法亲自解释https://bisq.wiki/Translation上写的情况。我更改了新翻译的接受度，现在他们需要征得许可。我希望这个错误不会再发生。
> 
> 1. 标记为“超链接”的字符串没有正确复制，超链接在应用程序中无法正常工作。见第一个图片链接，括号下的部分`[]`应该完全一样。
> 2. 标记为“no_translate”的字符串不应翻译。它们指的是未使用的altcoins，无法补偿。
> 3. 根据我有限的法语知识，一些翻译不正确，也没有修订预算。我分享的最后一张照片混淆了“你收到”和“你必须付钱”。我希望你和@Bayernatoor能合作修复错误的翻译。
> 4. 由于网站的很大一部分已经翻译，使用过去翻译的建议就足够了，整个网页翻译的预算为150美元。仍然缺少58根弦。
> 
> 我希望您在下一个周期继续翻译，并再次提出补偿请求，修复我现在认为不正确的所有细节。我知道你在这方面付出了一些努力，但目前我不能接受你的赔偿请求。我希望你理解。
> 
> ![图像](https://user-images.githubusercontent.com/50149324/100538230-badf1a80-322e-11eb-9aaf-dbb9dcc214e7.png)
> ![粘贴](https://user-images.githubusercontent.com/50149324/100538659-5f625c00-3231-11eb-81eb-8042d7e45197.png)
> ![粘贴（1）](https://user-images.githubusercontent.com/50149324/100538661-60938900-3231-11eb-90fa-d3a75592d44e.png)
> ![粘贴（2）](https://user-images.githubusercontent.com/50149324/100538662-60938900-3231-11eb-9de1-2f5e13eb2890.png)
> ![粘贴（3）](https://user-images.githubusercontent.com/50149324/100538663-612c1f80-3231-11eb-84d7-76e03acd6bcc.png)



> 拉斐尔你好，我不能批准这个赔偿请求。索赔请求迟迟提交，但最重要的是，原因我将在下面解释。在您大约6天前开始翻译之前，我们还没有交谈过，因此我无法亲自解释https://bisq.wiki/Translation上写的情况。我更改了新翻译的接受度，现在他们需要征得许可。我希望这个错误不会再发生。
> 
> 1. 标记为“超链接”的字符串没有正确复制，超链接在应用程序中无法正常工作。见第一个图片链接，括号下的部分`[]`应该完全一样。
> 2. 标记为“no_translate”的字符串不应翻译。它们指的是未使用的altcoins，无法补偿。
> 3. 根据我有限的法语知识，一些翻译不正确，也没有修订预算。我分享的最后一张照片混淆了“你收到”和“你必须付钱”。我希望你和@Bayernatoor能合作修复错误的翻译。
> 4. 由于网站的很大一部分已经翻译，使用过去翻译的建议就足够了，整个网页翻译的预算为150美元。仍然缺少58根弦。
> 
> 我希望您在下一个周期继续翻译，并再次提出补偿请求，修复我现在认为不正确的所有细节。我知道你在这方面付出了一些努力，但目前我不能接受你的赔偿请求。我希望你理解。
> 
> ![图像](https://user-images.githubusercontent.com/50149324/100538230-badf1a80-322e-11eb-9aaf-dbb9dcc214e7.png)
> ![粘贴](https://user-images.githubusercontent.com/50149324/100538659-5f625c00-3231-11eb-81eb-8042d7e45197.png)
> ![粘贴（1）](https://user-images.githubusercontent.com/50149324/100538661-60938900-3231-11eb-90fa-d3a75592d44e.png)
> ![粘贴（2）](https://user-images.githubusercontent.com/50149324/100538662-60938900-3231-11eb-9de1-2f5e13eb2890.png)
> ![粘贴（3）](https://user-images.githubusercontent.com/50149324/100538663-612c1f80-3231-11eb-84d7-76e03acd6bcc.png)




> 拉斐尔你好，我不能批准这个赔偿请求。索赔请求迟迟提交，但最重要的是，原因我将在下面解释。在您大约6天前开始翻译之前，我们还没有交谈过，因此我无法亲自解释https://bisq.wiki/Translation上写的情况。我更改了新翻译的接受度，现在他们需要征得许可。我希望这个错误不会再发生。
> 
> 1. 标记为“超链接”的字符串没有正确复制，超链接在应用程序中无法正常工作。见第一个图片链接，括号下的部分`[]`应该完全一样。
> 2. 标记为“no_translate”的字符串不应翻译。它们指的是未使用的altcoins，无法补偿。
> 3. 根据我有限的法语知识，一些翻译不正确，也没有修订预算。我分享的最后一张照片混淆了“你收到”和“你必须付钱”。我希望你和@Bayernatoor能合作修复错误的翻译。
> 4. 由于网站的很大一部分已经翻译，使用过去翻译的建议就足够了，整个网页翻译的预算为150美元。仍然缺少58根弦。
> 
> 我希望您在下一个周期继续翻译，并再次提出补偿请求，修复我现在认为不正确的所有细节。我知道你在这方面付出了一些努力，但目前我不能接受你的赔偿请求。我希望你理解。
> 
> ![图像](https://user-images.githubusercontent.com/50149324/100538230-badf1a80-322e-11eb-9aaf-dbb9dcc214e7.png)
> ![粘贴](https://user-images.githubusercontent.com/50149324/100538659-5f625c00-3231-11eb-81eb-8042d7e45197.png)
> ![粘贴（1）](https://user-images.githubusercontent.com/50149324/100538661-60938900-3231-11eb-90fa-d3a75592d44e.png)
> ![粘贴（2）](https://user-images.githubusercontent.com/50149324/100538662-60938900-3231-11eb-9de1-2f5e13eb2890.png)
> ![粘贴（3）](https://user-images.githubusercontent.com/50149324/100538663-612c1f80-3231-11eb-84d7-76e03acd6bcc.png)

Hello Mwithm,I can totally understand your decision. I have already read your reason carefully, that's true I have made some mistakes. I will deal with the "Hyperlink","no_translate"and some incorrect translation  mistakes immediately. The missing strings I will also try to complete them.
I am really sorry to put you through. I will finish it nicely next cycle. And thanks for your patience to let me know.

**Comment by MwithM** [comment]
What happened with the comment with chinese characters?

I count on you to keep translating for next cycle, on the meantime, I would appreciate that you come by Keybase to say hi and stay connected.

**Comment by MwithM** [comment]
Closed as not submitted
