### ISSUE TITLE
For May 2018

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/compensation#79]
## Summary

 - BSQ requested: 1020
 - BSQ address: B16kMZonmnNXrZvSqGuXVjpWWTZnSVG3xJb

## Contributions delivered

- [Payment Methods Slack](https://bisq.slack.com/messages/C89R6FQS3/) -> 300
- [Payment Methods Community](https://bisq.community/c/payment-methods) -> 150
- [Payment Methods Tracking and Report](https://docs.google.com/spreadsheets/d/1AeWAz5w_IzIQ3-QS9yEzZBOTH_83DT503IhLg_PQD10/edit?usp=sharing) -> 550
- BTC/CAD growth week -> 20

## Contributions in progress

- [Payment Methods Knowledge Base: Cash Deposit](https://github.com/bisq-network/bisq-docs/pull/52)
- [Payment Methods Knowledge Base: Revolut](https://github.com/bisq-network/bisq-docs/pull/51)
- [Adding Payeer] (https://github.com/bisq-network/payment-methods/issues/14)
- [Adding Moneygram] (https://github.com/bisq-network/payment-methods/issues/11)
- [Adding Serve] (https://github.com/bisq-network/payment-methods/issues/7)

## Roles performed

- Payment Methods Maintainter https://github.com/bisq-network/roles/issues/38

**Comment by cbeams** [comment]
Great stuff, @alfsbs. Thanks for sharing the graphs and other data on the payment method maintainer issue.

In future compensation requests, please link directly to the monthly report comment, instead of linking just to the issue itself. For example, this month, instead of linking like this:

> - Payment Methods Maintainter bisq-network/roles#38

You would have linked like this:

> - Payment Methods Maintainter: https://github.com/bisq-network/roles/issues/38#issuecomment-393504836

Doing it this way just makes it easier for stakeholders to click links and go directly to what they need to review when voting.

**Comment by cbeams** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/70#issuecomment-394830501.
