### ISSUE TITLE
For initial release of Bisq Trading API

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/compensation#8]
## Basic information

> _Specify the amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ amount requested: 11700
 - BSQ address: B1CZf25cS7KrGJnT8Z5uq8DbUApZLydCkj

## Details

> _Provide links to the work you are requesting compensation for, along with any comments or explanations that will help stakeholders understand its value._

**'Trading API'**, which is a HTTP API used to programmatically control a running Bisq instance. 
Use cases include automation of bitcoin/alt trades, market making, gathering offer information, etc.

If you want to see it in action, see this [example video](https://youtu.be/SkPT8bLOYtE).

[The API reference doc](https://mrosseel.github.io/bisq-api-examples/) is generated from the source code and is a very good starting point to get an idea of the functionality.

The main work was done in [a separate repository](https://github.com/mrosseel/bisq-api)

Sample code to access the API was provided in several languages. [This repository](https://github.com/mrosseel/bisq-api-examples) is also the place where example trading bots can be stored.

**Comment by cbeams** [comment]
Thanks for separating this out from #7, @mrosseel. Here's what I think might make the most sense:

Since this is really a compensation request for a particular deliverable (the Trading API), it doesn't really matter that it's "For September 2017". So, how about we update the title of this request issue to something like "For initial release of Bisq Trading API".

Then, @ManfredKarrer can answer the question whether he considered this work as already included in the October 6th testnet genesis distribution or not.

In any case, I would recommend that we don't attempt to include this particular request in the October voting period (i.e. the voting period that is beginning today), and rather, we can include it in the next voting period that will begin on December 1st. I'm making this latter recommendation mostly for simplicity's sake, such that we can say the voting period begins right now, without needing to wait for Manfred to weigh in about this, etc.

Sound OK?

**Comment by mrosseel** [comment]
pretty sure this was not included in the testnet distribution, but OK to not include it in the September voting.

**Comment by ManfredKarrer** [comment]
Yes the api work was not included in the genesis.
