### ISSUE TITLE
For May - June

### ISSUE THREAD

**Issue by Anderskargaard** [bisq-network/compensation#81]
## Summary

> _Specify the total amount of BSQ you are requesting, and the BSQ address that amount should be paid to:_

 - BSQ requested: 1025
 - BSQ address: B1MhJmVFgxYDGXBWE74396E9ZmSXLJupmSm

### YouTube exposure
Initiated a YouTube video stream with Manfred Karrer, Chris Beams and JW about DAOs and tokens that we chose to put on JWs channel, as he had more subscribers. This also went as out on World Crypto Networks podcast that has 5000 subscribers. The live stream was 2 hours. Apart from that there was preparation and promotion both before and after the stream. 
https://www.youtube.com/watch?v=YkLtt6ynLfQ&t=1847s
350 BSQ

Did a YouTube video on centralized vs decentralized exchanges after Bitfinex went KYC. Mentioned Bisq as an alternative to centralized exchanges and have URL visible in top of description under friends and sponsors:
https://youtu.be/3OdaTm6WH9o
40 BSQ

Having Bisq under friends and sponsors of my YouTube interview of Vortex:
https://youtu.be/XLQB6vCbpzg
10 BSQ

### Meetup related
E-mailing the 500+ members of my Los Angeles Century City Bitcoin Meetup mentioning Bisq. This is my Meetup:
https://www.meetup.com/Los-Angeles-Century-City-Bitcoin/
This was the text that was part of the e-mail going out in relation to Vortex speaking on Friday June 1st:
"www.bisq.network is a decentralized exchange with no custodial risk and it runs on Tor by default. They have been live for two years. A very interesting aspect is the fact that they have structured themselves as a DAO instead of raising millions in an ICO with no investor protection. So this might be a cutting organization structure that will replace ICOs."
100 BSQ

At the actual Meetup where Vortex was speaking:
1st June Pitching Bisq to my Meetup with focus on No custodial risk, no KYC/AML before which puts you at risk of landing on a "shopping list" for criminals on the dark market as a potential target
75 BSQ

### Bisq Internally
Giving SEO advice in our Slack under Ambassador mid May:
https://bisq.slack.com/messages/C8B2DJJNL/details/
150 BSQ

Participating in the growth call with Christoph and Manfred May 24th 2018. After the video stream we had a further good discussion about SEO and about how I can best help Bisq going forward. 
200 BSQ

Growth call 7th of June, I joined 7 minutes late.
100 BSQ

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

## Contributions in progress

Currently I am travelling and have limited time and broadband Internet. However from end July I will be able to start taking more responsibility on the growth call and start creating hands on workshop that I could travel with or attempt to scale to other people. Just an FYI.

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

## Roles performed

> _Provide links to your [monthly report](https://github.com/bisq-network/proposals/issues/13) on any roles you are responsible for._

**Comment by ManfredKarrer** [comment]
I am not sure if Tweets should be subject to compensation requests. 
Most contributors are active on Twitter and none has made a compensation request for that so far for that. It might send the wrong signal if we pay people for Tweets and it could attract the "social media marketing mafia" (I received many emails from "marketing "guys who offered Twitter or other social media activity with 100 000s of followers - the usual sock puppet army crap). 
Of course I am aware that you did not tweet with intention to get paid but because you support Bisq and that your followers are for sure a very valuable target audience for Bisq. It would be just hard to justify to not compensate someone else who show up and make a similar request.

Just my 5 cents. Others might have a different opinion...

**Comment by Anderskargaard** [comment]
Hi Manfred. Sorry for the delayed answer. I am travelling, but I did see your message. I hear your points and will delete the requests related to Twitter.

**Comment by ManfredKarrer** [comment]
@Anderskargaard Thanks for your understanding.

**Comment by cbeams** [comment]
@Anderskargaard, I think when it comes to "delivered" work, the "YouTube exposure"
and "Meetup related" items above are reasonable, because they are events that happened in the real world for the benefit of users.

I wouldn't call the "Bisq internal" items delivered work, though. Conversations in Slack aren't worth anything to users if they don't manifest in some delivered software or service or other material benefit to the network. In the SEO conversations we essentially decided on the status quo, i.e. non-action. So I think there's nothing _delivered_ to be claimed here. It's important to clearly distinguish delivery in this way, because we must avoid accidentally incentivizing internal chatter. Every conversation we have is a cost, not a delivered good. Ideally, we would deliver non-stop valuable improvements to the network with zero conversations required to do so, right?

What I do think is of value to the network, though, is conversations like this one where we figure this stuff out. Thanks.

**Comment by ripcurlx** [comment]
Closing as complete, see https://github.com/bisq-network/compensation/issues/82#issuecomment-402481195.

**Comment by Anderskargaard** [comment]
Not sure if I can write here now that the issue is closed, but I hear your points Chris and think it is a good idea to only focus on projects delivered. We will stay lean this way and avoid a run up in costs while we minimize the risk of useless chatter.

**Comment by cbeams** [comment]
Roger that, @Anderskargaard. Thanks.
