### ISSUE TITLE
For Cycle 27

### ISSUE THREAD

**Issue by flybylow** [bisq-network/compensation#890]
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`406`** 
- USD requested: 500
- BSQ rate: 1.23 USD per BSQ 
- Previous compensation request (if applicable): #  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| UX Designerorderbook | dev  | 500 | https://github.com/bisq-network/projects/issues/57 | here |

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by MwithM** [comment]
I guess that team must be dev. The parsing must be valid so please edit until it is.

**Comment by ripcurlx** [comment]
@chimp1984 could you please ACK this as soon as it is parsed valid? Thanks!

**Comment by chimp1984** [comment]
ACK

**Comment by MwithM** [comment]
Is this the correct TXID? 5e0ee7eb13783cc6eb611a7f3c702760ea6d1ce5e8b1f29b939e4dadbab3ac4f

**Comment by flybylow** [comment]
Sorry,
I was camping off-grid without access to my email. Is the first time i ask
for a compensation and is not the simplest flow so might need some help.

Do i need to make the request again with ACK as team?

My wallet address: Bbc1qng253uf2pcrfcsckh8h5har4u2d6jjmzjq8p92

Regards,
Ward

Op di 24 aug. 2021 om 11:40 schreef MwithM ***@***.***>:

**Comment by MwithM** [comment]
You don't need to share any BSQ address, that is handled by Bisq software when doing a proposal. There is a 406BSQ proposal under this handle at the Bisq DAO.

![imagen](https://user-images.githubusercontent.com/50149324/130741779-12f2ce94-c6d4-4419-abf7-fa44767b6243.png)

DAO voters should check that the one who submitted the proposal to the DAO has access to the same keybase handle by posting the correct TXID of the proposal. You can look for other accepted proposals to see how is it by yourself.

I think that your proposal will be accepted anyway though, since it's for a small amount and there are no other proposals under your handle.

**Comment by flybylow** [comment]
Thanks for the information. I do not need to take any action from my side
then.


Op wo 25 aug. 2021 om 09:00 schreef MwithM ***@***.***>:

**Comment by ghost** [comment]
## Issuance by Team:
|team|amount BSQ|amount USD|
|---|---|---|
|dev|406.00|500.00|

Total Issuance: 406.00 BSQ (equivalent to: 500.00 USD)

**Comment by MwithM** [comment]
Closed as accepted, even if was not parsed as valid. 
I edited your request until it was valid (by adding "dev" and "500" USD). Please, on next cycle makes sure your compensation is good for the parsing bot.
